### ISSUE TITLE
Dependant cached resources

### ISSUE THREAD

**Issue by bakura10** [yonathan06/solid-cached-resource#2]
Hi :),

I'm completely new to SolidJs and I am a bit lost in how everything works. I've spent a few hours but I felt it might be easier to ask :).

I would like to have one resource depending from another:

```
export const getResourcesList = () => {
  return createCachedResource(
    () => [],
    async () => {
      return await (await authenticatedFetch('/resources')).json();
    }
  );
}

export const getResourceById = (id) => {
  return createCachedResource(
    () => [getResourcesList(), id()],
    async ([resources, id]) => {
      // This is where I am not able to understand
    }
  )
}
```

In my component, the first one works perfectly. However, the second one, simply never works:

```
export default function Nested() {
  const params = useParams(),
    [resource] = getResourceById(() => params.id);

  return (
    <Suspense>
      {resource().name}
    </Suspense>
  )
}
```

I must be missing something very obvious here.

Thanks!

**Comment by yonathan06** [comment]
@bakura10 notice that getResourcesList is returning a cachedResource which is an array and not a reactive signal
I guess that what you would want to do is:
```JS
export const getResourceById = (id) => {
  const [resources] = getResourcesList();
  return createCachedResource(
    () => [resources(), id()],
    async ([resources, id]) => {
      // This is where I am not able to understand
    }
  )
}
```

**Comment by bakura10** [comment]
Hi @yonathan06 . Thanks for the answer, this was indeed that. I will need some time to adjust, the way of thinking of Solid has really nothing in common with everything I know so far! :D
