### ISSUE TITLE
Reactivity doesn't seem to be working

### ISSUE THREAD

**Issue by aryzing** [yonathan06/solid-cached-resource#4]
I've created this [reproduction repo](https://github.com/aryzing/repro-broken-reactivity-solid-cached-resource) with 3 components. All 3 load the same resource. When the first 2 mount, the "API" is only hit once as expected. The third one mounts and unmounts with a timer. Whenever it mounts, a new value from the "API" is fetched and displayed within this third component, but the other two do not get the updated value.

**Comment by yonathan06** [comment]
@aryzing thank you for the repro project, it helped a lot
I released a new version with a fix, please check it

**Comment by aryzing** [comment]
Thanks for the fix, working as expected
