### ISSUE TITLE
Type resource as possibly undefined

### ISSUE THREAD

**Issue by aryzing** [yonathan06/solid-cached-resource#5]
When first rendering a resource, it may be undefined, but the types don't seem to suggest that it may be undefined.

For example, the below code won't report any TS errors when omitting the optional chaining `?.`. Although, if omitted, calling `user().name` will crash the app.

https://github.com/aryzing/repro-broken-reactivity-solid-cached-resource/blob/bc6fa07aa38bb1ef23849d99f120655cc121dae7/src/components/one.tsx#L10

Shouldn't resources be typed as `| undefined`?

**Comment by yonathan06** [comment]
It has the same types as the original resource created, so I think it should be fixed in solidjs lib
